### ISSUE TITLE
Show channel and date in bot messages

### ISSUE THREAD

**Issue by mgwalker** [18F/standup-bot#106]
As a user, I'd like the bot to tell me which channel it's asking about so that I know what channel I'm answering for.

**Comment by mgwalker** [comment]
Tried a few different arrangements.  Here are some screenshots with comments:

---

<img width="810" alt="screen shot 2016-12-15 at 8 11 08 am" src="https://cloud.githubusercontent.com/assets/1775733/21227232/995fede8-c29e-11e6-9897-4344260d29b3.png">

The original idea was to put the channel name and day of the week at the start of each of the bot's questions during the interview.  But it's easy not to notice the channel name and the day of the week being there is confusing - it kind of looks like the bot is asking about what I did Wednesday.

---

<img width="807" alt="screen shot 2016-12-15 at 8 12 35 am" src="https://cloud.githubusercontent.com/assets/1775733/21227284/dc121742-c29e-11e6-83eb-95ada125afc0.png">

Took out the day of the week.  Now the channel name _really_ disappears.

---

<img width="810" alt="screen shot 2016-12-15 at 8 11 37 am" src="https://cloud.githubusercontent.com/assets/1775733/21227335/22d53448-c29f-11e6-8a5b-40f132179ae8.png">

Moved everything to the end.  The channel name stands out more, but I think having the day of the week here is even _more_ confusing.

---

<img width="808" alt="screen shot 2016-12-15 at 8 11 47 am" src="https://cloud.githubusercontent.com/assets/1775733/21227399/7096275a-c29f-11e6-9404-04c2036ac1ae.png">

Just the channel name at the end.  I think this one is the clearest of the four here.

---

Maybe changing the text from just the day of the week to something more descriptive would help, but I'm worried that having a day name and the word "yesterday" in the same sentence is going to throw people off, especially since they won't match up.  (E.g., "Yesterday was Tuesday...  so...  should I put in today since it's asking for Wednesday?")

Thoughts, anyone?

**Comment by stvnrlly** [comment]
The concern about the date/day mismatch makes sense to me. I wonder if the underlying issue this is addressing—people responding to stale interviews—was mostly fixed with the queue, in which case the simple fourth option seems like a good idea for a first iteration, at least.

Another approach is to incorporate the channel name directly into the message to encourage people to scope their standup to the channel. For example, "What did you do yesterday for #standup-bot-dev?"

**Comment by mgwalker** [comment]
I think you're right that this was mostly addressed with the queue.  If people have issues with it again, we can always open a new issue.
