### ISSUE TITLE
Add report command to show a week's standups for a user

### ISSUE THREAD

**Issue by lauraGgit** [18F/standup-bot#13]
Standups help me jog my memory for tock. The bot may make it easier through by just having a list of DMs or it may make it harder to find my own standups. I'm not sure what solution I'm proposing, I would just like to still be able to find my weeks' standups.

**Comment by stvnrlly** [comment]
Definitely. Storing the standups in a database should make some sort of `@standupbot report` command possible.

What sort of report would be useful to you? Would it mostly be the "Yesterday" entries related to the period, or would something else help?

**Comment by vdavez** [comment]
I made a card with a specific user story to describe this scenario. https://github.com/18F/standup-bot/issues/56 @lauraGgit, does this capture what you're thinking?

**Comment by lauraGgit** [comment]
@vzvenyach that looks like what I am thinking.

**Comment by vdavez** [comment]
Duplicate of #56.
