### ISSUE TITLE
Emoji-ing a message in the DM with the bot makes things crazy

### ISSUE THREAD

**Issue by stvnrlly** [18F/standup-bot#131]
If a user adds an emoji reaction to any message in the DM, the bot now seems to think that there's an unfinished standup for #deleted-channel. Because there's no channel and no actual standup, it's not possible to exit the standup, which means that its not possible to DM with the bot about the real standup.

(h/t @adelevie for finding this one)

**Comment by arsenio** [comment]
I've seen the same thing happen to me and others on my team. One workaround _seems_ to be the ability to submit a standup report in one formatted DM message.

**Comment by stvnrlly** [comment]
@arsenio Thanks for that feedback!

🤔 A potential fix could be to check that the emoji'd message isn't in a DM before doing anything else.
