### ISSUE TITLE
Check timezone

### ISSUE THREAD

**Issue by stvnrlly** [18F/standup-bot#15]
Because who knows what the server is running on. This also could be important for teams not based in EST.

**Comment by mgwalker** [comment]
This is pretty tough.  You can store all times in UTC but how do you know what timezone users are in?  Maybe the user's timezone is in the `message.user` property somewhere.  Then if you convert from the user's timezone to UTC and work exclusively from UTC, that should normalize things.  But that assumes the user's timezone information is on the `message.user` property.

**Comment by stvnrlly** [comment]
I think converting to UTC is the best bet right now. It doesn't look like there's any way to get the timezone from the user, so I think for now it should assume EST but allow other timezones to be set.
