### ISSUE TITLE
Offer to move standup before overwriting an existing one

### ISSUE THREAD

**Issue by stvnrlly** [18F/standup-bot#16]
That seems like plenty. There could be a `@standup-bot move standup` command to handle this. If there's no standup, it should create one.

Also if somebody tries to create a standup when one exists, the bot should offer to move it. This could use the `bot.convo()` feature.

**Comment by mgwalker** [comment]
It looks like it moves the existing standup already.  (Just kinda playing around with it, if I create two standups in a channel, it only reports at the time of the last one.)  Even if that's correct, the second part would still be a cool addition.

**Comment by stvnrlly** [comment]
This is likely a false report because I was able to create two standups simultaneously when two instances of the bot were running. I'll convert it to only be about that confirmation step.
