### ISSUE TITLE
User Feedback - additional functionality - Opportunity to edit after sending info to stand-up bot

### ISSUE THREAD

**Issue by randyhart** [18F/standup-bot#18]
As a user, it would be nice to be able to change/add/edit stand-up information in the time between sending it to the stand-up bot and the time it is posted in the daily stand-up report.

For example, if there was something that a user forgot to add to their stand-up, and they think it's really important, can they interact with the bot to request a change to what they just submitted.  (might be too clunky, just an idea).

**Comment by stvnrlly** [comment]
This is already supported, but should be made clear in usage instructions.

Say the initial message is 

```
standup #mychannel
y: i did things
t: i'll do things
```

A later message like 

```
standup #mychannel
b: hyperion is closed
```

will add that "Blocker" entry without changing the other stuff

A later message like 

```
standup #mychannel
y: i did three things
```

will overwrite the previous "Yesterday" entry with the new one.

The harder issue is #6, where a user tries to change the standup message by editing the initial one.
