### ISSUE TITLE
Is it possible to capture offline messages?

### ISSUE THREAD

**Issue by mgwalker** [18F/standup-bot#44]
If the bot is offline for some reason, it would be great if it could capture messages sent to it when it comes back online.  This may be a Slack API limitation.

**Comment by vdavez** [comment]
Better solution: keep bot online.

**Comment by mgwalker** [comment]
Bot sure stays online better than it used to.  @stvnrlly: Should we close this?  The answer to the original question is no.

**Comment by stvnrlly** [comment]
Yeah, I think so.
