### ISSUE TITLE
feature ideas to help people remember to stand up

### ISSUE THREAD

**Issue by quepol** [18F/standup-bot#46]
`@standup-bot what time is standup` [default = in this channel]
`DM @standup-bot what time is standup in #outreach`
`@standup-bot remind me`

**Comment by stvnrlly** [comment]
I _think_ that these features are all implemented, though they should be documented when you say `@standup-bot help`. The formats are `@standup-bot when` and `@standup-bot reminder [number of minutes before standup]`.

**Comment by mgwalker** [comment]
This one is implemented, and the documentation was updated a while back.  It's still not super clear, but it's a whole other issue of how to format the help in a way that makes it more accessible!
