### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by stvnrlly** [18F/standup-bot#5]

**Comment by mgwalker** [comment]
To facilitate testing, should it also be broken into modules?

**Comment by mgwalker** [comment]
Also (let me flood your inbox with Github stuff), do you have any preferences for testing frameworks/assertion libraries/etc.?  I'm personally fond of [tap](https://www.npmjs.com/package/tap) but I'm happier using the consensus pick over a personal favorite.  :stuck_out_tongue:

**Comment by stvnrlly** [comment]
I am definitely pro-module. Typically, I put them in the `lib` directory.

As for a the library, I am agnostic. I think the team is most familiar with Mocha? We may want to try something that has Cucumber integration and write the tests that way as an exercise.

**Comment by mgwalker** [comment]
Ooh, neat idea on Cucumber stuff.  I like that!

**Comment by mgwalker** [comment]
Closed by #12, #26, #35, #37
