### ISSUE TITLE
Prepare some documentation for use of standup-bot

### ISSUE THREAD

**Issue by vdavez** [18F/standup-bot#59]

**Comment by mgwalker** [comment]
Considering 18F pages or something along those lines.  Wherever it goes, it can also be the home of eventual API documentation.

**Comment by vdavez** [comment]
We'll be using the built-in express server to power the landing page.

**Comment by vdavez** [comment]
As a new user, I want an intuitive web site that describes the functionalities of standup-bot, so that I can participate in the next standup.

**Comment by mgwalker** [comment]
Closed by #80 and #97
