### ISSUE TITLE
Handle message editing

### ISSUE THREAD

**Issue by stvnrlly** [18F/standup-bot#6]
When a user edits a standup in the bot DM, it should be updated in the DB if appropriate.

This may be built in to `botkit`, but hasn't been tested yet.

**Comment by stvnrlly** [comment]
Am I right that https://github.com/18F/standup-bot/commit/29bedc1f1c38c51a3c6e22eb1f488b8afd38c647 deals only with pre-report editing? My thought was that the bot would update its report if the standup was edited after the fact. I'm not sure if that's wise, though.

**Comment by mgwalker** [comment]
It treats an edited message just like a new message.  I suppose the issue you raise exists before and after this PR, though.  There's nothing stopping someone from sending an update after the report...  Hmm.  Should we open another issue for that?

**Comment by stvnrlly** [comment]
Yep, :+1:  I'll open another issue.
