### ISSUE TITLE
Handle late submissions outside of the edit window

### ISSUE THREAD

**Issue by stvnrlly** [18F/standup-bot#61]
When the bot tries to update the report outside of the edit window, it fails. Handling the error is easy, but we should discuss what happens. There are a few options:
1. Give the user an error message and not record anything
2. Give the user an error message, but still record the standup silently
3. Post the standup as a standalone bot message
4. Re-run the full standup report for the day

The third (posting a standalone message) seems the most likely choice, but I'm curious whether anybody else has opinions about this.

**Comment by mgwalker** [comment]
I think the third option also makes the most sense.

I wonder if at some point, when there's an API, it would make sense to expose higher-granularity configurations that way.  Allow different channels to have different settings for things like this?  I dunno, just thinking into the textbox.

**Comment by stvnrlly** [comment]
The downside of the third option is that it leaves the summary card in the original report untouched, which could be confusing in some cases.

There's no reason we couldn't re-run the summary card and add the standalone report to it, though.

**Comment by vdavez** [comment]
I agree with option 3.

**Comment by vdavez** [comment]
`As a late submitter, I want others to see my report so that they know what I'm up to.`

`As a team member, I want to see new reports but I don't want to get overwhelmed with the same information I already saw, so I can focus.`

**Comment by mgwalker** [comment]
This one seems to have magically fixed itself due to changes in how Slack processes bot messages.  @stvnrlly: Agree?

**Comment by stvnrlly** [comment]
Agreed, and hopefully it stays that way.
