### ISSUE TITLE
Schedule standups for particular days of the week

### ISSUE THREAD

**Issue by mgwalker** [18F/standup-bot#85]
As a user, I want to be able to specify which days of the week to run a standup so that I will not be bothered on days that standup is not applicable.

E.g.,
`@standup-bot create standup 1300 m t th f`

**Comment by mgwalker** [comment]
@mogul Does this capture the behavior you want?

**Comment by mogul** [comment]
Yes, that would be enormously helpful. A further iteration would be to let me skip certain days in particular weeks, eg something like:
`@standup-bot create standup 1300 m 2t th f`

...would only fire on every _other_ Tuesday. (There's probably a more standard way to specify this, eg by using whatever `cron` uses.)
