### ISSUE TITLE
Ask users if they have availability

### ISSUE THREAD

**Issue by mgwalker** [18F/standup-bot#86]
As a user, I want the bot to ask me if I have availability so I can indicate my status without using a cryptic emoji.

**Comment by stvnrlly** [comment]
This is another situation where botkit's [utterances](https://github.com/howdyai/botkit#included-utterances) come in handy.

Additionally, if we wrap the bot in a Slack app, we can use [message buttons](https://api.slack.com/docs/message-buttons) to make this a bit simpler of an interaction.

**Comment by mgwalker** [comment]
Obsoleted by #122
